# Generated by Django 4.2.6 on 2023-10-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('price_total', models.PositiveIntegerField(verbose_name='Total price')),
                ('price_paid', models.PositiveIntegerField(default=0, verbose_name='Price paid')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='waiting', max_length=10, verbose_name='Status')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='packages.package', verbose_name='Package')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='packages.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
