# Generated by Django 4.2.6 on 2023-10-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Unique name for the user')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('individual_pin', models.CharField(max_length=14, verbose_name='Individual PIN number')),
                ('serial_number', models.CharField(max_length=9, verbose_name='Passport serial number')),
                ('region', models.CharField(max_length=128, verbose_name='Region/City')),
                ('district', models.CharField(max_length=128, verbose_name='District')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name', 'middle_name'], name='accounts_us_last_na_720a17_idx'),
        ),
    ]
