# Generated by Django 4.2.6 on 2023-11-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
        ('packages', '0008_alter_flight_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Phone number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/accounts/profile_photos/%Y/%m/', verbose_name='Profile photo')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='images/accounts/passports/%Y/%m/%d/', verbose_name='Passport picture')),
                ('individual_pin', models.CharField(blank=True, max_length=14, null=True, verbose_name='Individual PIN number')),
                ('serial_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport serial number')),
                ('district', models.CharField(blank=True, max_length=128, null=True, verbose_name='District')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('liked_packages', models.ManyToManyField(blank=True, related_name='liked_users', to='packages.package', verbose_name='Liked packages')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.region', verbose_name='Region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='VerifiedPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Verified phone number',
                'verbose_name_plural': 'Verified phone numbers',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired status')),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP codes',
                'unique_together': {('phone_number', 'code', 'is_expired')},
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('is_phone_number_same', models.BooleanField(verbose_name='Is phone number the same?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='images/accounts/passports/%Y/%m/%d/', verbose_name='Passport picture')),
                ('individual_pin', models.CharField(blank=True, max_length=14, null=True, verbose_name='Individual PIN number')),
                ('serial_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport serial number')),
                ('district', models.CharField(max_length=128, verbose_name='District')),
                ('is_address_same', models.BooleanField(verbose_name='Is address the same?')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_users', to='base.region', verbose_name='Region/City')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_people', to=settings.AUTH_USER_MODEL, verbose_name='Responsible person')),
            ],
            options={
                'verbose_name': 'Related person',
                'verbose_name_plural': 'Related people',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='accounts_re_last_na_d00979_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='accounts_us_last_na_ddbf2c_idx'),
        ),
    ]
