# Generated by Django 4.2.6 on 2023-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone_number', 'code', 'is_expired'], name='accounts_ot_phone_n_74bd50_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedphonenumber',
            index=models.Index(fields=['phone_number'], name='accounts_ve_phone_n_610bfa_idx'),
        ),
    ]
