# Generated by Django 4.2.6 on 2023-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='passport_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/accounts/passports/%Y/%m/%d/', verbose_name='Passport picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='individual_pin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Individual PIN number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport serial number'),
        ),
    ]
