# Generated by Django 4.2.6 on 2023-10-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedphonenumber',
            options={'verbose_name': 'Verified phone number', 'verbose_name_plural': 'Verified phone numbers'},
        ),
        migrations.AddField(
            model_name='otpcode',
            name='device_id',
            field=models.CharField(default='123', max_length=64, verbose_name='Device ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifiedphonenumber',
            name='device_id',
            field=models.CharField(default='123', max_length=64, verbose_name='Device ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='verifiedphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone number'),
        ),
    ]
