# Generated by Django 4.2.6 on 2023-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_verifiedphonenumber_options_otpcode_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterUniqueTogether(
            name='verifiedphonenumber',
            unique_together={('device_id', 'phone_number')},
        ),
    ]
