# Generated by Django 4.2.6 on 2023-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='images/accounts/passports/%Y/%m/%d/', verbose_name='Passport picture')),
                ('individual_pin', models.CharField(blank=True, max_length=14, null=True, verbose_name='Individual PIN number')),
                ('serial_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport serial number')),
                ('region', models.CharField(max_length=128, verbose_name='Region/City')),
                ('district', models.CharField(max_length=128, verbose_name='District')),
            ],
            options={
                'verbose_name': 'Related person',
                'verbose_name_plural': 'Related people',
                'indexes': [models.Index(fields=['last_name', 'first_name', 'middle_name'], name='accounts_re_last_na_85937d_idx')],
            },
        ),
    ]
