# Generated by Django 4.2.6 on 2023-10-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_verifiedphonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verifiedphonenumber',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='verifiedphonenumber',
            name='device_id',
        ),
    ]
