# Generated by Django 4.2.6 on 2023-10-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0006_relatedperson_is_address_same_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedperson',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.region', verbose_name='Region/City'),
        ),
    ]
