# Generated by Django 4.2.6 on 2023-10-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0008_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedperson',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_users', to='base.region', verbose_name='Region/City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.region', verbose_name='Region'),
        ),
    ]
