# Generated by Django 4.2.6 on 2023-10-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0009_alter_relatedperson_region_alter_user_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.region', verbose_name='Region'),
        ),
    ]
