# Generated by Django 4.2.6 on 2023-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relatedperson',
            name='accounts_re_last_na_85937d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_last_na_720a17_idx',
        ),
        migrations.RemoveField(
            model_name='relatedperson',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['last_name', 'first_name'], name='accounts_re_last_na_d00979_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='accounts_us_last_na_ddbf2c_idx'),
        ),
    ]
