# Generated by Django 4.2.6 on 2023-10-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_relatedperson_accounts_re_last_na_85937d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/accounts/profile_photos/%Y/%m/', verbose_name='Profile photo'),
        ),
    ]
