# Generated by Django 4.2.6 on 2023-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='will_receive',
            field=models.BooleanField(default=True, verbose_name='Will receive?'),
        ),
    ]
