# Generated by Django 4.2.6 on 2023-11-07 01:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images/about/icons/', verbose_name='Icon')),
                ('link', models.URLField(verbose_name='Link or username')),
            ],
            options={
                'verbose_name': 'Social media account',
                'verbose_name_plural': 'Social media accounts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='iFrame')),
                ('latitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Longitude')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='base.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
