# Generated by Django 4.2.6 on 2023-12-05 11:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_phonenumber_is_active_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Terms and conditions')),
            ],
            options={
                'verbose_name': 'Terms and conditions',
                'verbose_name_plural': 'Terms and conditions',
            },
        ),
    ]
