# Generated by Django 4.2.6 on 2023-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_frequentlyaskedquestion_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title'),
        ),
    ]
