# Generated by Django 4.2.6 on 2023-12-20 07:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_socialmedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_uk',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_uk',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions'),
        ),
    ]
