# Generated by Django 4.2.6 on 2023-10-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_day_destination_accommodation_alter_destination_city_and_more'),
        ('accommodations', '0002_remove_city_country_alter_accommodation_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
