# Generated by Django 4.2.6 on 2023-10-28 20:52

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('address_uz', models.CharField(max_length=256, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(max_length=256, null=True, verbose_name='Address')),
                ('address_en', models.CharField(max_length=256, null=True, verbose_name='Address')),
                ('landmark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark')),
                ('landmark_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark')),
                ('landmark_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark')),
                ('landmark_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='iFrame')),
                ('latitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='images/packages/packages/%Y/%m/', verbose_name='Picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('core_activities', models.ManyToManyField(blank=True, related_name='packages', to='packages.activity', verbose_name='Core activities')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.ImageField(upload_to='images/packages/features/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Plan feature',
                'verbose_name_plural': 'Plan features',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Plan type',
                'verbose_name_plural': 'Plan types',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('activities', models.ManyToManyField(blank=True, related_name='plans', to='packages.activity', verbose_name='Plan-specific activities')),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='packages.packagefeature', verbose_name='Features')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='packages.package', verbose_name='Package')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='packages.plantype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='core_features',
            field=models.ManyToManyField(blank=True, related_name='packages', to='packages.packagefeature', verbose_name='Core features'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in days')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.city', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.country', verbose_name='Country')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
