# Generated by Django 4.2.6 on 2023-10-12 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('landmark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='iFrame')),
                ('latitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='images/packages/packages/%Y/%m/', verbose_name='Picture')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End date')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.city', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.ImageField(upload_to='images/packages/features/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Plan feature',
                'verbose_name_plural': 'Plan features',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Plan type',
                'verbose_name_plural': 'Plan types',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('activities', models.ManyToManyField(blank=True, related_name='plans', to='packages.activity', verbose_name='Activities')),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='packages.planfeature', verbose_name='Features')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='packages.package', verbose_name='Package')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='packages.plantype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
