# Generated by Django 4.2.6 on 2023-10-12 10:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
    ]
