# Generated by Django 4.2.6 on 2023-10-30 15:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationfeature',
            options={'verbose_name': 'Accommodation feature', 'verbose_name_plural': 'Accommodation features'},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='long_description',
            field=ckeditor.fields.RichTextField(default=None, verbose_name='Long description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='short_description',
            field=models.TextField(default=None, verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is popular?'),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('due_time', models.TimeField(verbose_name='Flight time')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='packages.accommodation', verbose_name='Accommodation')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='packages.day', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Stay',
                'verbose_name_plural': 'Stays',
            },
        ),
    ]
