# Generated by Django 4.2.6 on 2023-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
