# Generated by Django 4.2.6 on 2023-10-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_accommodationfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='activities',
        ),
        migrations.AlterField(
            model_name='flight',
            name='due_time',
            field=models.TimeField(verbose_name='Due time'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='due_time',
            field=models.TimeField(verbose_name='Due time'),
        ),
        migrations.CreateModel(
            name='ActivityPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('picture', models.ImageField(upload_to='images/packages/activities/%Y/%m', verbose_name='Picture')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='packages.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity picture',
                'verbose_name_plural': 'Activity pictures',
            },
        ),
        migrations.CreateModel(
            name='ActivityBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_time', models.TimeField(verbose_name='Due time')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bridges', to='packages.activity', verbose_name='Activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.day', verbose_name='Day')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Activity in Day',
                'verbose_name_plural': 'Activities in Day',
            },
        ),
    ]
