# Generated by Django 4.2.6 on 2023-10-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_description_en_package_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='core_activities',
        ),
    ]
