# Generated by Django 4.2.6 on 2023-10-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discount expiry date'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price in USD ($)'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('package', 'type')},
        ),
    ]
