# Generated by Django 4.2.6 on 2023-10-30 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_plan_discount_expiry_date_alter_plan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
    ]
