# Generated by Django 4.2.6 on 2023-10-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_core_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('picture', models.ImageField(upload_to='images/packages/package/%Y/%m/', verbose_name='Picture')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Package picture',
                'verbose_name_plural': 'Package pictures',
            },
        ),
    ]
