# Generated by Django 4.2.6 on 2023-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packagepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationfeature',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
