# Generated by Django 4.2.6 on 2023-10-17 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('packages', '0006_activity_address_en_activity_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='city',
        ),
        migrations.AddField(
            model_name='package',
            name='core_activities',
            field=models.ManyToManyField(blank=True, related_name='packages', to='packages.activity', verbose_name='Core activities'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='plans', to='packages.activity', verbose_name='Plan-specific cctivities'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in days')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.city', verbose_name='City')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
