# Generated by Django 4.2.6 on 2023-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_accommodationpicture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='picture',
        ),
        migrations.AddField(
            model_name='packagepicture',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main?'),
        ),
    ]
