# Generated by Django 4.2.6 on 2023-10-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_remove_city_country_alter_accommodation_city_and_more'),
        ('base', '0002_country_city'),
        ('packages', '0006_package_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('activities', models.ManyToManyField(related_name='days', to='packages.activity', verbose_name='Activities')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='accommodations.accommodation', verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='base.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='base.country', verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('flight_time', models.TimeField(verbose_name='Flight time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='packages.day', verbose_name='Day')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_flights', to='base.city', verbose_name='From what city?')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_flights', to='base.city', verbose_name='To what city?')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'FLights',
            },
        ),
    ]
