# Generated by Django 4.2.6 on 2023-10-28 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('packages', '0007_remove_package_city_package_core_activities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='package',
            name='country',
        ),
        migrations.RemoveField(
            model_name='package',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accommodations.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='plans', to='packages.activity', verbose_name='Plan-specific activities'),
        ),
    ]
