# Generated by Django 4.2.6 on 2023-10-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_remove_package_picture_packagepicture_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
    ]
