# Generated by Django 4.2.6 on 2023-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_flight_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['title'], name='packages_pa_title_3c83c2_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active'], name='packages_pa_is_acti_b8b41a_idx'),
        ),
    ]
