# Generated by Django 4.2.6 on 2023-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_rename_active_package_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanFeature',
            new_name='PackageFeature',
        ),
        migrations.AddField(
            model_name='package',
            name='core_features',
            field=models.ManyToManyField(blank=True, related_name='packages', to='packages.packagefeature', verbose_name='Core features'),
        ),
    ]
