# Generated by Django 4.2.6 on 2023-11-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_package_packages_pa_title_3c83c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='embedded_link',
            field=models.TextField(blank=True, null=True, verbose_name='Embedded Map link'),
        ),
    ]
