# Generated by Django 4.2.6 on 2023-11-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_accommodation_embedded_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('day_number',), 'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('start_date',), 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_from',
            field=models.CharField(default='Toshkent', max_length=128, verbose_name='Flight from'),
        ),
    ]
