# Generated by Django 4.2.6 on 2023-11-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('packages', '0011_alter_day_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='flight_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='base.region', verbose_name='Region'),
        ),
    ]
