# Generated by Django 4.2.6 on 2023-11-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('packages', '0017_remove_trip_flight_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flight_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='base.region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
