# Generated by Django 4.2.6 on 2023-11-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('packages', '0018_trip_flight_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='base.country', verbose_name='Country'),
        ),
    ]
