# Generated by Django 4.2.6 on 2023-11-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_alter_trip_flight_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagefeature',
            options={'verbose_name': 'Package feature', 'verbose_name_plural': 'Package features'},
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('package', 'day_number')},
        ),
        migrations.RemoveField(
            model_name='day',
            name='trip',
        ),
    ]
