# Generated by Django 4.2.6 on 2023-11-30 03:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_alter_packagefeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='long_description_cr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Long description'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='short_description_cr',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='description_cr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='accommodationfeature',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='activity',
            name='address_cr',
            field=models.CharField(max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_cr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='activity',
            name='landmark_cr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_cr',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='package',
            name='description_cr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='package',
            name='title_cr',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='packagefeature',
            name='description_cr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='packagefeature',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_cr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='plantype',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
