# Generated by Django 4.2.6 on 2023-11-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_accommodation_long_description_cr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='long_description_cr',
            new_name='long_description_uk',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='short_description_cr',
            new_name='short_description_uk',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='accommodationfeature',
            old_name='description_cr',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='accommodationfeature',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='address_cr',
            new_name='address_uk',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='description_cr',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='landmark_cr',
            new_name='landmark_uk',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='description_cr',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='packagefeature',
            old_name='description_cr',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='packagefeature',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='description_cr',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='plantype',
            old_name='title_cr',
            new_name='title_uk',
        ),
    ]
