# Generated by Django 4.2.6 on 2023-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_rename_long_description_cr_accommodation_long_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_discount_active',
            field=models.BooleanField(default=True, verbose_name='Discount status'),
        ),
    ]
