# Generated by Django 4.2.6 on 2023-11-30 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_package_duration_plan_is_discount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 30), verbose_name='End date'),
        ),
    ]
