# Generated by Django 4.2.6 on 2023-11-30 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0026_alter_trip_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Corresponding date'),
        ),
    ]
