# Generated by Django 4.2.6 on 2023-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0027_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default="Mashg'ulot", max_length=128, verbose_name='Activity type'),
        ),
    ]
