# Generated by Django 4.2.6 on 2023-12-08 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_trip'),
        ('base', '0003_rename_title_cr_city_title_uk_and_more'),
        ('packages', '0028_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('start_date',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='package',
            name='flight_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='base.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
