# Generated by Django 4.2.6 on 2023-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0029_alter_package_options_package_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='address_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='address_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='address_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='address_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='landmark_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='landmark_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='landmark_uk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='landmark_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type_en',
            field=models.CharField(default="Mashg'ulot", max_length=128, null=True, verbose_name='Activity type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type_ru',
            field=models.CharField(default="Mashg'ulot", max_length=128, null=True, verbose_name='Activity type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type_uk',
            field=models.CharField(default="Mashg'ulot", max_length=128, null=True, verbose_name='Activity type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type_uz',
            field=models.CharField(default="Mashg'ulot", max_length=128, null=True, verbose_name='Activity type'),
        ),
    ]
