# Generated by Django 4.2.6 on 2023-11-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='title_cr',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
