# Generated by Django 4.2.6 on 2023-11-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_city_title_cr_country_title_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='title_cr',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='title_cr',
            new_name='title_uk',
        ),
    ]
