# Generated by Django 4.2.6 on 2023-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for verification'), ('verified', 'Verified'), ('canceled', 'Canceled')], default='waiting', max_length=10, verbose_name='Status'),
        ),
    ]
