# Generated by Django 4.2.6 on 2023-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
    ]
