# Generated by Django 4.2.6 on 2023-10-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Popular place',
                'verbose_name_plural': 'Popular places',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main status')),
                ('picture', models.ImageField(upload_to='images/places/', verbose_name='Picture')),
                ('popular_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='places.popularplace')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'unique_together': {('popular_place', 'is_main')},
            },
        ),
    ]
