# Generated by Django 4.2.6 on 2023-10-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplace',
            name='description',
            field=models.TextField(default='Nothing, just nothing', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularplace',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/places/', verbose_name='Picture'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
