# Generated by Django 4.2.6 on 2023-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main status'),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('popular_place', 'is_main')},
        ),
    ]
