# Generated by Django 4.2.6 on 2023-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplace',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
    ]
