# Generated by Django 4.2.6 on 2023-10-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPagePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='images/gallery/main_page/', verbose_name='Picture')),
                ('prompt', models.CharField(max_length=256, verbose_name='Text prompt')),
                ('active', models.BooleanField(default=True, verbose_name='Active status')),
            ],
            options={
                'verbose_name': 'Main page picture',
                'verbose_name_plural': 'Main page pictures',
            },
        ),
    ]
