# Generated by Django 4.2.6 on 2023-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mainpagepictures',
            index=models.Index(fields=['active'], name='gallery_mai_active_abf735_idx'),
        ),
    ]
