# Generated by Django 4.2.6 on 2023-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_mainpagepictures_gallery_mai_active_abf735_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mainpagepictures',
            name='gallery_mai_active_abf735_idx',
        ),
        migrations.RenameField(
            model_name='mainpagepictures',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddIndex(
            model_name='mainpagepictures',
            index=models.Index(fields=['is_active'], name='gallery_mai_is_acti_0d092d_idx'),
        ),
    ]
