# Generated by Django 4.2.6 on 2023-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_mainpagepictures_gallery_mai_active_abf735_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagepictures',
            name='prompt_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Text prompt'),
        ),
        migrations.AddField(
            model_name='mainpagepictures',
            name='prompt_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Text prompt'),
        ),
        migrations.AddField(
            model_name='mainpagepictures',
            name='prompt_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Text prompt'),
        ),
        migrations.AddField(
            model_name='mainpagepictures',
            name='prompt_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Text prompt'),
        ),
    ]
